### PR TITLE
word: Export word generic methods.

### PR DESCRIPTION
**Pull request by cwebber**
Here's why I'm doing this: I'm working on some meta-word usage.  A few uses:

 - Unit tests for words
 - Wrapping words in "debug words" that can capture inputs and states and roll forward and backward in time for a variety of games
 - words that contain words
 - etc etc

### CODE REVIEW

**Comment by cwebber** [comment]
This is exported in a submodule in my PR.  I'm not sure everyone will want it all the time, hence the submodule.  I would be ok with it being in the primary module's provide statement, however.

**Comment by jeapostrophe** [comment]
I think everyone can enjoy these. Can you export them generally and add them to the docs if necessary?

**Comment by cwebber** [comment]
Yup, will do!

**Comment by cwebber** [comment]
Updated the PR.  The docs appear to already describe the methods so I didn't update them.

**Comment by jeapostrophe** [comment]
Awesome! Thank you!

**Comment by cwebber** [comment]
Hey, I noticed these got reverted in commit 6e341803e694149480a768fa2ee7bca334d00399 with the commit message:

> Revert generics... breaks stuff?

What did it break?

**Comment by cwebber** [comment]
It would be good to get it added back since I have good use for this!

**Comment by cwebber** [comment]
We could go the route of exporting in the submodule per my original design if that would simplify things.

**Comment by jeapostrophe** [comment]
I'm cool with that

**Pull request merged**
