### PR TITLE
Add support for positions x, y of a window on a specified monitor (or the current one)

### PR DESCRIPTION
**Pull request by Metaxal**

### CODE REVIEW

**Comment by jeapostrophe** [comment]
Awesome! Thank you

**Comment by Metaxal** [comment]
My pleasure. Thanks for merging.

I just noticed that I forgot to remove the unused `bazaar/debug' require in
gui/utils.rkt. (I can't submit a fix right now as I must avoid pushing
commits from work.)

**Comment by jeapostrophe** [comment]
I think I fixed it?

**Comment by Metaxal** [comment]
Yes indeed this should fix it.

**Comment by Metaxal** [comment]
Also just in case: I just realized that nonnegative-integer? in utils.rkt
is a new binding, but it's safe (and probably better) to replace it with
exact-nonnegative-integer? in case you want to support older versions of
racket.

**Pull request merged**
